# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  Default

steps:

- script: 
    npm install
  displayName: 'Depedency Installation'

#- task: Npm@1
#  inputs:
#    command: 'custom'
#   customCommand: 'ng build --prod --verbose'

- task: CmdLine@2
  inputs:
    script: 'npm install -g @angular/cli'


# Archieving Build Artifacts Files

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(Build.Repository.LocalPath)/dist'
#    includeRootFolder: true
#    archiveType: 'zip'
#    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#    replaceExistingArchive: true



#  Publishing Artifacts

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'symphony-summitai'
    publishLocation: 'Container'


